<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Travel Recommendations - RoamRadar</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
        }
        .header h1 {
            color: #3498db;
            margin: 0;
        }
        .search-criteria {
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 30px;
        }
        .search-criteria h2 {
            color: #3498db;
            margin-top: 0;
            font-size: 18px;
        }
        .destination {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }
        .destination h3 {
            color: #3498db;
            margin-bottom: 10px;
        }
        .destination p {
            margin: 5px 0;
        }
        .tags {
            margin-top: 10px;
        }
        .tag {
            display: inline-block;
            background-color: #e9f7fe;
            color: #3498db;
            padding: 3px 8px;
            border-radius: 3px;
            margin-right: 5px;
            font-size: 12px;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 12px;
            color: #777;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>RoamRadar Travel Recommendations</h1>
    </div>

    <div class="search-criteria">
        <h2>Your Search Criteria</h2>
        <p><strong>Budget:</strong> ${{ number_format($budget, 2) }}</p>
        <p><strong>Travel Dates:</strong> {{ date('F j, Y', strtotime($startDate)) }} - {{ date('F j, Y', strtotime($endDate)) }}</p>
        <p><strong>Selected Activities:</strong> {{ implode(', ', array_map('ucfirst', $activities)) }}</p>
    </div>

    <h2>Recommended Destinations</h2>

    @if(count($destinations) > 0)
        @foreach($destinations as $destination)
            <div class="destination">
                <h3>{{ $destination['name'] }}</h3>
                <p><strong>Description:</strong> {{ $destination['description'] }}</p>
                <p><strong>Estimated Cost:</strong> ${{ number_format($destination['cost'], 2) }}</p>
                
                <div class="tags">
                    <strong>Activities:</strong>
                    @foreach($destination['tags'] as $tag)
                        <span class="tag">{{ ucfirst($tag) }}</span>
                    @endforeach
                </div>
            </div>
        @endforeach
    @else
        <p>No destinations found matching your criteria. Try adjusting your budget or selecting different activities.</p>
    @endif

    <div class="footer">
        <p>Generated by RoamRadar on {{ date('F j, Y') }}</p>
    </div>
</body>
</html> 